package com.mshz.webflux.dto;

public enum NotifAction {
    // Audit actions
    AUDIT_STARTED, AUDIT_EXECUTED, AUDIT_SUBMITTED, 
    AUDIT_COMPLETED, AUDIT_CANCELED, AUDIT_ON_PAUSE, AUDIT_INITILIZED,

    // recommandation actions
    RECOM_STARTED, RECOM_EXECUTED, RECOM_SUBMITTED, 
    RECOM_COMPLETED, RECOM_CANCELED, RECOM_ON_PAUSE, RECOM_INITILIZED,
}
